import { AlgorithmCode } from '@/types/algorithm';

export const fibonacciCode: Record<string, AlgorithmCode> = {
  javascript: {
    language: 'javascript',
    lines: [
      'function fibonacci(n) {',
      '  // Base cases',
      '  if (n <= 1) return n;',
      '  ',
      '  // Memoization table',
      '  const dp = new Array(n + 1);',
      '  dp[0] = 0;',
      '  dp[1] = 1;',
      '  ',
      '  // Fill the table',
      '  for (let i = 2; i <= n; i++) {',
      '    dp[i] = dp[i - 1] + dp[i - 2];',
      '  }',
      '  ',
      '  return dp[n];',
      '}',
    ],
  },
  python: {
    language: 'python',
    lines: [
      'def fibonacci(n):',
      '    # Base cases',
      '    if n <= 1:',
      '        return n',
      '    ',
      '    # Memoization table',
      '    dp = [0] * (n + 1)',
      '    dp[0] = 0',
      '    dp[1] = 1',
      '    ',
      '    # Fill the table',
      '    for i in range(2, n + 1):',
      '        dp[i] = dp[i - 1] + dp[i - 2]',
      '    ',
      '    return dp[n]',
    ],
  },
  pseudocode: {
    language: 'pseudocode',
    lines: [
      'FIBONACCI(n)',
      '  if n ≤ 1',
      '    return n',
      '  ',
      '  dp = array of size n + 1',
      '  dp[0] = 0',
      '  dp[1] = 1',
      '  ',
      '  for i = 2 to n',
      '    dp[i] = dp[i - 1] + dp[i - 2]',
      '  ',
      '  return dp[n]',
    ],
  },
};
