import { AlgorithmCode } from '@/types/algorithm';

export const bfsCode: Record<string, AlgorithmCode> = {
  javascript: {
    language: 'javascript',
    lines: [
      'function bfs(graph, start) {',
      '  const visited = new Set();',
      '  const queue = [start];',
      '  const result = [];',
      '  ',
      '  visited.add(start);',
      '  ',
      '  while (queue.length > 0) {',
      '    const node = queue.shift();',
      '    result.push(node);',
      '    ',
      '    // Visit all neighbors',
      '    for (const neighbor of graph[node]) {',
      '      if (!visited.has(neighbor)) {',
      '        visited.add(neighbor);',
      '        queue.push(neighbor);',
      '      }',
      '    }',
      '  }',
      '  ',
      '  return result;',
      '}',
    ],
  },
  python: {
    language: 'python',
    lines: [
      'def bfs(graph, start):',
      '    visited = set()',
      '    queue = [start]',
      '    result = []',
      '    ',
      '    visited.add(start)',
      '    ',
      '    while queue:',
      '        node = queue.pop(0)',
      '        result.append(node)',
      '        ',
      '        # Visit all neighbors',
      '        for neighbor in graph[node]:',
      '            if neighbor not in visited:',
      '                visited.add(neighbor)',
      '                queue.append(neighbor)',
      '    ',
      '    return result',
    ],
  },
  pseudocode: {
    language: 'pseudocode',
    lines: [
      'BFS(graph, start)',
      '  visited = empty set',
      '  queue = [start]',
      '  result = []',
      '  ',
      '  add start to visited',
      '  ',
      '  while queue is not empty',
      '    node = dequeue from queue',
      '    append node to result',
      '    ',
      '    for each neighbor of node',
      '      if neighbor not in visited',
      '        add neighbor to visited',
      '        enqueue neighbor',
      '  ',
      '  return result',
    ],
  },
};

export const dfsCode: Record<string, AlgorithmCode> = {
  javascript: {
    language: 'javascript',
    lines: [
      'function dfs(graph, start) {',
      '  const visited = new Set();',
      '  const result = [];',
      '  ',
      '  function dfsHelper(node) {',
      '    visited.add(node);',
      '    result.push(node);',
      '    ',
      '    // Visit all neighbors',
      '    for (const neighbor of graph[node]) {',
      '      if (!visited.has(neighbor)) {',
      '        dfsHelper(neighbor);',
      '      }',
      '    }',
      '  }',
      '  ',
      '  dfsHelper(start);',
      '  return result;',
      '}',
    ],
  },
  python: {
    language: 'python',
    lines: [
      'def dfs(graph, start):',
      '    visited = set()',
      '    result = []',
      '    ',
      '    def dfs_helper(node):',
      '        visited.add(node)',
      '        result.append(node)',
      '        ',
      '        # Visit all neighbors',
      '        for neighbor in graph[node]:',
      '            if neighbor not in visited:',
      '                dfs_helper(neighbor)',
      '    ',
      '    dfs_helper(start)',
      '    return result',
    ],
  },
  pseudocode: {
    language: 'pseudocode',
    lines: [
      'DFS(graph, start)',
      '  visited = empty set',
      '  result = []',
      '  ',
      '  DFS-HELPER(node)',
      '    add node to visited',
      '    append node to result',
      '    ',
      '    for each neighbor of node',
      '      if neighbor not in visited',
      '        DFS-HELPER(neighbor)',
      '  ',
      '  DFS-HELPER(start)',
      '  return result',
    ],
  },
};
