import { AlgorithmCode } from '@/types/algorithm';

export const knapsack01Code: Record<string, AlgorithmCode> = {
  javascript: {
    language: 'javascript',
    lines: [
      'function knapsack01(weights, values, capacity) {',
      '  const n = weights.length;',
      '  const dp = Array(n + 1).fill(null)',
      '    .map(() => Array(capacity + 1).fill(0));',
      '  ',
      '  for (let i = 1; i <= n; i++) {',
      '    for (let w = 0; w <= capacity; w++) {',
      '      if (weights[i - 1] <= w) {',
      '        dp[i][w] = Math.max(',
      '          dp[i - 1][w],',
      '          dp[i - 1][w - weights[i - 1]] + values[i - 1]',
      '        );',
      '      } else {',
      '        dp[i][w] = dp[i - 1][w];',
      '      }',
      '    }',
      '  }',
      '  ',
      '  return dp[n][capacity];',
      '}',
    ],
  },
  python: {
    language: 'python',
    lines: [
      'def knapsack_01(weights, values, capacity):',
      '    n = len(weights)',
      '    dp = [[0] * (capacity + 1) for _ in range(n + 1)]',
      '    ',
      '    for i in range(1, n + 1):',
      '        for w in range(capacity + 1):',
      '            if weights[i - 1] <= w:',
      '                dp[i][w] = max(',
      '                    dp[i - 1][w],',
      '                    dp[i - 1][w - weights[i - 1]] + values[i - 1]',
      '                )',
      '            else:',
      '                dp[i][w] = dp[i - 1][w]',
      '    ',
      '    return dp[n][capacity]',
    ],
  },
  pseudocode: {
    language: 'pseudocode',
    lines: [
      'KNAPSACK-01(weights, values, capacity)',
      '  n = length(weights)',
      '  dp = 2D array of size (n+1) x (capacity+1), all zeros',
      '  ',
      '  for i = 1 to n',
      '    for w = 0 to capacity',
      '      if weights[i-1] ≤ w',
      '        dp[i][w] = max(dp[i-1][w],',
      '                      dp[i-1][w-weights[i-1]] + values[i-1])',
      '      else',
      '        dp[i][w] = dp[i-1][w]',
      '  ',
      '  return dp[n][capacity]',
    ],
  },
};
