import { AlgorithmCode } from '@/types/algorithm';

export const knightTourCode: Record<string, AlgorithmCode> = {
  javascript: {
    language: 'javascript',
    lines: [
      'function solveKnightTour(n, startX, startY) {',
      '  const board = Array(n).fill(-1).map(() => Array(n).fill(-1));',
      '  const dx = [2, 1, -1, -2, -2, -1, 1, 2];',
      '  const dy = [1, 2, 2, 1, -1, -2, -2, -1];',
      '  ',
      '  function isSafe(x, y) {',
      '    return x >= 0 && x < n && y >= 0 && y < n',
      '           && board[x][y] === -1;',
      '  }',
      '  ',
      '  function solve(x, y, moveCount) {',
      '    if (moveCount === n * n) return true;',
      '    ',
      '    for (let i = 0; i < 8; i++) {',
      '      const nextX = x + dx[i];',
      '      const nextY = y + dy[i];',
      '      ',
      '      if (isSafe(nextX, nextY)) {',
      '        board[nextX][nextY] = moveCount;',
      '        if (solve(nextX, nextY, moveCount + 1))',
      '          return true;',
      '        board[nextX][nextY] = -1; // backtrack',
      '      }',
      '    }',
      '    return false;',
      '  }',
      '  ',
      '  board[startX][startY] = 0;',
      '  if (solve(startX, startY, 1)) return board;',
      '  return null;',
      '}',
    ],
  },
  python: {
    language: 'python',
    lines: [
      'def solve_knight_tour(n, start_x, start_y):',
      '    board = [[-1] * n for _ in range(n)]',
      '    dx = [2, 1, -1, -2, -2, -1, 1, 2]',
      '    dy = [1, 2, 2, 1, -1, -2, -2, -1]',
      '    ',
      '    def is_safe(x, y):',
      '        return (0 <= x < n and 0 <= y < n',
      '                and board[x][y] == -1)',
      '    ',
      '    def solve(x, y, move_count):',
      '        if move_count == n * n:',
      '            return True',
      '        ',
      '        for i in range(8):',
      '            next_x = x + dx[i]',
      '            next_y = y + dy[i]',
      '            ',
      '            if is_safe(next_x, next_y):',
      '                board[next_x][next_y] = move_count',
      '                if solve(next_x, next_y, move_count + 1):',
      '                    return True',
      '                board[next_x][next_y] = -1  # backtrack',
      '        return False',
      '    ',
      '    board[start_x][start_y] = 0',
      '    if solve(start_x, start_y, 1):',
      '        return board',
      '    return None',
    ],
  },
  pseudocode: {
    language: 'pseudocode',
    lines: [
      'SOLVE-KNIGHT-TOUR(n, startX, startY)',
      '  board = n×n matrix of -1',
      '  dx = [2, 1, -1, -2, -2, -1, 1, 2]',
      '  dy = [1, 2, 2, 1, -1, -2, -2, -1]',
      '  ',
      '  IS-SAFE(x, y)',
      '    return x ≥ 0 and x < n and y ≥ 0 and y < n',
      '           and board[x][y] = -1',
      '  ',
      '  SOLVE(x, y, moveCount)',
      '    if moveCount = n × n',
      '      return true',
      '    ',
      '    for i = 0 to 7',
      '      nextX = x + dx[i]',
      '      nextY = y + dy[i]',
      '      ',
      '      if IS-SAFE(nextX, nextY)',
      '        board[nextX][nextY] = moveCount',
      '        if SOLVE(nextX, nextY, moveCount + 1)',
      '          return true',
      '        board[nextX][nextY] = -1  // backtrack',
      '    return false',
      '  ',
      '  board[startX][startY] = 0',
      '  if SOLVE(startX, startY, 1)',
      '    return board',
      '  return null',
    ],
  },
};
