import { AlgorithmCode } from '@/types/algorithm';

export const lcsCode: Record<string, AlgorithmCode> = {
  javascript: {
    language: 'javascript',
    lines: [
      'function lcs(str1, str2) {',
      '  const m = str1.length, n = str2.length;',
      '  const dp = Array(m + 1).fill(null)',
      '    .map(() => Array(n + 1).fill(0));',
      '  ',
      '  for (let i = 1; i <= m; i++) {',
      '    for (let j = 1; j <= n; j++) {',
      '      if (str1[i - 1] === str2[j - 1]) {',
      '        dp[i][j] = dp[i - 1][j - 1] + 1;',
      '      } else {',
      '        dp[i][j] = Math.max(dp[i - 1][j], dp[i][j - 1]);',
      '      }',
      '    }',
      '  }',
      '  ',
      '  // Backtrack to find LCS',
      '  let lcsStr = "";',
      '  let i = m, j = n;',
      '  while (i > 0 && j > 0) {',
      '    if (str1[i - 1] === str2[j - 1]) {',
      '      lcsStr = str1[i - 1] + lcsStr;',
      '      i--; j--;',
      '    } else if (dp[i - 1][j] > dp[i][j - 1]) {',
      '      i--;',
      '    } else {',
      '      j--;',
      '    }',
      '  }',
      '  ',
      '  return { length: dp[m][n], lcs: lcsStr };',
      '}',
    ],
  },
  python: {
    language: 'python',
    lines: [
      'def lcs(str1, str2):',
      '    m, n = len(str1), len(str2)',
      '    dp = [[0] * (n + 1) for _ in range(m + 1)]',
      '    ',
      '    for i in range(1, m + 1):',
      '        for j in range(1, n + 1):',
      '            if str1[i - 1] == str2[j - 1]:',
      '                dp[i][j] = dp[i - 1][j - 1] + 1',
      '            else:',
      '                dp[i][j] = max(dp[i - 1][j], dp[i][j - 1])',
      '    ',
      '    # Backtrack to find LCS',
      '    lcs_str = ""',
      '    i, j = m, n',
      '    while i > 0 and j > 0:',
      '        if str1[i - 1] == str2[j - 1]:',
      '            lcs_str = str1[i - 1] + lcs_str',
      '            i -= 1',
      '            j -= 1',
      '        elif dp[i - 1][j] > dp[i][j - 1]:',
      '            i -= 1',
      '        else:',
      '            j -= 1',
      '    ',
      '    return dp[m][n], lcs_str',
    ],
  },
  pseudocode: {
    language: 'pseudocode',
    lines: [
      'LCS(str1, str2)',
      '  m = length(str1), n = length(str2)',
      '  dp = 2D array of size (m+1) x (n+1), all zeros',
      '  ',
      '  for i = 1 to m',
      '    for j = 1 to n',
      '      if str1[i-1] == str2[j-1]',
      '        dp[i][j] = dp[i-1][j-1] + 1',
      '      else',
      '        dp[i][j] = max(dp[i-1][j], dp[i][j-1])',
      '  ',
      '  // Backtrack to find LCS string',
      '  lcs_str = ""',
      '  i = m, j = n',
      '  while i > 0 and j > 0',
      '    if str1[i-1] == str2[j-1]',
      '      prepend str1[i-1] to lcs_str',
      '      i--, j--',
      '    else if dp[i-1][j] > dp[i][j-1]',
      '      i--',
      '    else',
      '      j--',
      '  ',
      '  return dp[m][n], lcs_str',
    ],
  },
};
