import { AlgorithmCode } from '@/types/algorithm';

export const ratMazeCode: Record<string, AlgorithmCode> = {
  javascript: {
    language: 'javascript',
    lines: [
      'function solveMaze(maze, n) {',
      '  const solution = Array(n).fill(0).map(() => Array(n).fill(0));',
      '  ',
      '  function isSafe(x, y) {',
      '    return x >= 0 && x < n && y >= 0 && y < n',
      '           && maze[x][y] === 1;',
      '  }',
      '  ',
      '  function solve(x, y) {',
      '    if (x === n - 1 && y === n - 1) {',
      '      solution[x][y] = 1;',
      '      return true;',
      '    }',
      '    ',
      '    if (isSafe(x, y)) {',
      '      solution[x][y] = 1;',
      '      ',
      '      // Move right',
      '      if (solve(x, y + 1)) return true;',
      '      ',
      '      // Move down',
      '      if (solve(x + 1, y)) return true;',
      '      ',
      '      // Backtrack',
      '      solution[x][y] = 0;',
      '      return false;',
      '    }',
      '    return false;',
      '  }',
      '  ',
      '  if (solve(0, 0)) return solution;',
      '  return null;',
      '}',
    ],
  },
  python: {
    language: 'python',
    lines: [
      'def solve_maze(maze, n):',
      '    solution = [[0] * n for _ in range(n)]',
      '    ',
      '    def is_safe(x, y):',
      '        return (0 <= x < n and 0 <= y < n',
      '                and maze[x][y] == 1)',
      '    ',
      '    def solve(x, y):',
      '        if x == n - 1 and y == n - 1:',
      '            solution[x][y] = 1',
      '            return True',
      '        ',
      '        if is_safe(x, y):',
      '            solution[x][y] = 1',
      '            ',
      '            # Move right',
      '            if solve(x, y + 1):',
      '                return True',
      '            ',
      '            # Move down',
      '            if solve(x + 1, y):',
      '                return True',
      '            ',
      '            # Backtrack',
      '            solution[x][y] = 0',
      '            return False',
      '        return False',
      '    ',
      '    if solve(0, 0):',
      '        return solution',
      '    return None',
    ],
  },
  pseudocode: {
    language: 'pseudocode',
    lines: [
      'SOLVE-MAZE(maze, n)',
      '  solution = n×n matrix of zeros',
      '  ',
      '  IS-SAFE(x, y)',
      '    return x ≥ 0 and x < n and y ≥ 0 and y < n',
      '           and maze[x][y] = 1',
      '  ',
      '  SOLVE(x, y)',
      '    if x = n-1 and y = n-1  // destination',
      '      solution[x][y] = 1',
      '      return true',
      '    ',
      '    if IS-SAFE(x, y)',
      '      solution[x][y] = 1',
      '      ',
      '      if SOLVE(x, y+1)  // move right',
      '        return true',
      '      ',
      '      if SOLVE(x+1, y)  // move down',
      '        return true',
      '      ',
      '      solution[x][y] = 0  // backtrack',
      '      return false',
      '    return false',
      '  ',
      '  if SOLVE(0, 0)',
      '    return solution',
      '  return null',
    ],
  },
};
