import { AlgorithmCode } from '@/types/algorithm';

export const linearSearchCode: Record<string, AlgorithmCode> = {
  javascript: {
    language: 'javascript',
    lines: [
      'function linearSearch(arr, target) {',
      '  for (let i = 0; i < arr.length; i++) {',
      '    // Check current element',
      '    if (arr[i] === target) {',
      '      return i; // Found!',
      '    }',
      '  }',
      '  ',
      '  return -1; // Not found',
      '}',
    ],
  },
  python: {
    language: 'python',
    lines: [
      'def linear_search(arr, target):',
      '    for i in range(len(arr)):',
      '        # Check current element',
      '        if arr[i] == target:',
      '            return i  # Found!',
      '    ',
      '    return -1  # Not found',
    ],
  },
  pseudocode: {
    language: 'pseudocode',
    lines: [
      'LINEAR-SEARCH(A, target)',
      '  for i = 0 to length(A) - 1',
      '    if A[i] = target',
      '      return i',
      '  ',
      '  return -1',
    ],
  },
};

export const binarySearchCode: Record<string, AlgorithmCode> = {
  javascript: {
    language: 'javascript',
    lines: [
      'function binarySearch(arr, target) {',
      '  let left = 0;',
      '  let right = arr.length - 1;',
      '  ',
      '  while (left <= right) {',
      '    const mid = Math.floor((left + right) / 2);',
      '    ',
      '    if (arr[mid] === target) {',
      '      return mid; // Found!',
      '    }',
      '    ',
      '    if (arr[mid] < target) {',
      '      left = mid + 1; // Search right half',
      '    } else {',
      '      right = mid - 1; // Search left half',
      '    }',
      '  }',
      '  ',
      '  return -1; // Not found',
      '}',
    ],
  },
  python: {
    language: 'python',
    lines: [
      'def binary_search(arr, target):',
      '    left = 0',
      '    right = len(arr) - 1',
      '    ',
      '    while left <= right:',
      '        mid = (left + right) // 2',
      '        ',
      '        if arr[mid] == target:',
      '            return mid  # Found!',
      '        ',
      '        if arr[mid] < target:',
      '            left = mid + 1  # Search right half',
      '        else:',
      '            right = mid - 1  # Search left half',
      '    ',
      '    return -1  # Not found',
    ],
  },
  pseudocode: {
    language: 'pseudocode',
    lines: [
      'BINARY-SEARCH(A, target)',
      '  left = 0',
      '  right = length(A) - 1',
      '  ',
      '  while left ≤ right',
      '    mid = floor((left + right) / 2)',
      '    ',
      '    if A[mid] = target',
      '      return mid',
      '    ',
      '    if A[mid] < target',
      '      left = mid + 1',
      '    else',
      '      right = mid - 1',
      '  ',
      '  return -1',
    ],
  },
};
