import { AlgorithmCode } from '@/types/algorithm';

export const bubbleSortCode: Record<string, AlgorithmCode> = {
  javascript: {
    language: 'javascript',
    lines: [
      'function bubbleSort(arr) {',
      '  const n = arr.length;',
      '  ',
      '  for (let i = 0; i < n - 1; i++) {',
      '    for (let j = 0; j < n - i - 1; j++) {',
      '      // Compare adjacent elements',
      '      if (arr[j] > arr[j + 1]) {',
      '        // Swap elements',
      '        [arr[j], arr[j + 1]] = [arr[j + 1], arr[j]];',
      '      }',
      '    }',
      '  }',
      '  ',
      '  return arr;',
      '}',
    ],
  },
  python: {
    language: 'python',
    lines: [
      'def bubble_sort(arr):',
      '    n = len(arr)',
      '    ',
      '    for i in range(n - 1):',
      '        for j in range(n - i - 1):',
      '            # Compare adjacent elements',
      '            if arr[j] > arr[j + 1]:',
      '                # Swap elements',
      '                arr[j], arr[j + 1] = arr[j + 1], arr[j]',
      '    ',
      '    return arr',
    ],
  },
  pseudocode: {
    language: 'pseudocode',
    lines: [
      'BUBBLE-SORT(A)',
      '  n = length(A)',
      '  ',
      '  for i = 0 to n-2',
      '    for j = 0 to n-i-2',
      '      if A[j] > A[j+1]',
      '        swap A[j] and A[j+1]',
      '  ',
      '  return A',
    ],
  },
};

export const selectionSortCode: Record<string, AlgorithmCode> = {
  javascript: {
    language: 'javascript',
    lines: [
      'function selectionSort(arr) {',
      '  const n = arr.length;',
      '  ',
      '  for (let i = 0; i < n - 1; i++) {',
      '    let minIdx = i;',
      '    ',
      '    // Find minimum in unsorted portion',
      '    for (let j = i + 1; j < n; j++) {',
      '      if (arr[j] < arr[minIdx]) {',
      '        minIdx = j;',
      '      }',
      '    }',
      '    ',
      '    // Swap minimum with current position',
      '    if (minIdx !== i) {',
      '      [arr[i], arr[minIdx]] = [arr[minIdx], arr[i]];',
      '    }',
      '  }',
      '  ',
      '  return arr;',
      '}',
    ],
  },
  python: {
    language: 'python',
    lines: [
      'def selection_sort(arr):',
      '    n = len(arr)',
      '    ',
      '    for i in range(n - 1):',
      '        min_idx = i',
      '        ',
      '        # Find minimum in unsorted portion',
      '        for j in range(i + 1, n):',
      '            if arr[j] < arr[min_idx]:',
      '                min_idx = j',
      '        ',
      '        # Swap minimum with current position',
      '        if min_idx != i:',
      '            arr[i], arr[min_idx] = arr[min_idx], arr[i]',
      '    ',
      '    return arr',
    ],
  },
  pseudocode: {
    language: 'pseudocode',
    lines: [
      'SELECTION-SORT(A)',
      '  n = length(A)',
      '  ',
      '  for i = 0 to n-2',
      '    minIdx = i',
      '    ',
      '    for j = i+1 to n-1',
      '      if A[j] < A[minIdx]',
      '        minIdx = j',
      '    ',
      '    if minIdx ≠ i',
      '      swap A[i] and A[minIdx]',
      '  ',
      '  return A',
    ],
  },
};

export const quickSortCode: Record<string, AlgorithmCode> = {
  javascript: {
    language: 'javascript',
    lines: [
      'function quickSort(arr, low = 0, high = arr.length - 1) {',
      '  if (low < high) {',
      '    // Partition the array',
      '    const pivotIdx = partition(arr, low, high);',
      '    ',
      '    // Recursively sort left portion',
      '    quickSort(arr, low, pivotIdx - 1);',
      '    ',
      '    // Recursively sort right portion',
      '    quickSort(arr, pivotIdx + 1, high);',
      '  }',
      '  return arr;',
      '}',
      '',
      'function partition(arr, low, high) {',
      '  const pivot = arr[high];',
      '  let i = low - 1;',
      '  ',
      '  for (let j = low; j < high; j++) {',
      '    if (arr[j] <= pivot) {',
      '      i++;',
      '      [arr[i], arr[j]] = [arr[j], arr[i]];',
      '    }',
      '  }',
      '  ',
      '  [arr[i + 1], arr[high]] = [arr[high], arr[i + 1]];',
      '  return i + 1;',
      '}',
    ],
  },
  python: {
    language: 'python',
    lines: [
      'def quick_sort(arr, low=0, high=None):',
      '    if high is None:',
      '        high = len(arr) - 1',
      '    ',
      '    if low < high:',
      '        # Partition the array',
      '        pivot_idx = partition(arr, low, high)',
      '        ',
      '        # Recursively sort left portion',
      '        quick_sort(arr, low, pivot_idx - 1)',
      '        ',
      '        # Recursively sort right portion',
      '        quick_sort(arr, pivot_idx + 1, high)',
      '    ',
      '    return arr',
      '',
      'def partition(arr, low, high):',
      '    pivot = arr[high]',
      '    i = low - 1',
      '    ',
      '    for j in range(low, high):',
      '        if arr[j] <= pivot:',
      '            i += 1',
      '            arr[i], arr[j] = arr[j], arr[i]',
      '    ',
      '    arr[i + 1], arr[high] = arr[high], arr[i + 1]',
      '    return i + 1',
    ],
  },
  pseudocode: {
    language: 'pseudocode',
    lines: [
      'QUICKSORT(A, low, high)',
      '  if low < high',
      '    pivotIdx = PARTITION(A, low, high)',
      '    QUICKSORT(A, low, pivotIdx - 1)',
      '    QUICKSORT(A, pivotIdx + 1, high)',
      '  return A',
      '',
      'PARTITION(A, low, high)',
      '  pivot = A[high]',
      '  i = low - 1',
      '  ',
      '  for j = low to high - 1',
      '    if A[j] ≤ pivot',
      '      i = i + 1',
      '      swap A[i] and A[j]',
      '  ',
      '  swap A[i + 1] and A[high]',
      '  return i + 1',
    ],
  },
};

export const insertionSortCode: Record<string, AlgorithmCode> = {
  javascript: {
    language: 'javascript',
    lines: [
      'function insertionSort(arr) {',
      '  for (let i = 1; i < arr.length; i++) {',
      '    const key = arr[i];',
      '    let j = i - 1;',
      '    ',
      '    // Shift elements greater than key',
      '    while (j >= 0 && arr[j] > key) {',
      '      arr[j + 1] = arr[j];',
      '      j--;',
      '    }',
      '    ',
      '    // Insert key at correct position',
      '    arr[j + 1] = key;',
      '  }',
      '  ',
      '  return arr;',
      '}',
    ],
  },
  python: {
    language: 'python',
    lines: [
      'def insertion_sort(arr):',
      '    for i in range(1, len(arr)):',
      '        key = arr[i]',
      '        j = i - 1',
      '        ',
      '        # Shift elements greater than key',
      '        while j >= 0 and arr[j] > key:',
      '            arr[j + 1] = arr[j]',
      '            j -= 1',
      '        ',
      '        # Insert key at correct position',
      '        arr[j + 1] = key',
      '    ',
      '    return arr',
    ],
  },
  pseudocode: {
    language: 'pseudocode',
    lines: [
      'INSERTION-SORT(A)',
      '  for i = 1 to length(A) - 1',
      '    key = A[i]',
      '    j = i - 1',
      '    ',
      '    while j >= 0 and A[j] > key',
      '      A[j + 1] = A[j]',
      '      j = j - 1',
      '    ',
      '    A[j + 1] = key',
      '  ',
      '  return A',
    ],
  },
};

export const mergeSortCode: Record<string, AlgorithmCode> = {
  javascript: {
    language: 'javascript',
    lines: [
      'function mergeSort(arr) {',
      '  if (arr.length <= 1) return arr;',
      '  ',
      '  const mid = Math.floor(arr.length / 2);',
      '  const left = mergeSort(arr.slice(0, mid));',
      '  const right = mergeSort(arr.slice(mid));',
      '  ',
      '  return merge(left, right);',
      '}',
      '',
      'function merge(left, right) {',
      '  const result = [];',
      '  let i = 0, j = 0;',
      '  ',
      '  while (i < left.length && j < right.length) {',
      '    if (left[i] <= right[j]) {',
      '      result.push(left[i++]);',
      '    } else {',
      '      result.push(right[j++]);',
      '    }',
      '  }',
      '  ',
      '  return result.concat(left.slice(i)).concat(right.slice(j));',
      '}',
    ],
  },
  python: {
    language: 'python',
    lines: [
      'def merge_sort(arr):',
      '    if len(arr) <= 1:',
      '        return arr',
      '    ',
      '    mid = len(arr) // 2',
      '    left = merge_sort(arr[:mid])',
      '    right = merge_sort(arr[mid:])',
      '    ',
      '    return merge(left, right)',
      '',
      'def merge(left, right):',
      '    result = []',
      '    i, j = 0, 0',
      '    ',
      '    while i < len(left) and j < len(right):',
      '        if left[i] <= right[j]:',
      '            result.append(left[i])',
      '            i += 1',
      '        else:',
      '            result.append(right[j])',
      '            j += 1',
      '    ',
      '    return result + left[i:] + right[j:]',
    ],
  },
  pseudocode: {
    language: 'pseudocode',
    lines: [
      'MERGE-SORT(A)',
      '  if length(A) ≤ 1',
      '    return A',
      '  ',
      '  mid = floor(length(A) / 2)',
      '  left = MERGE-SORT(A[0...mid])',
      '  right = MERGE-SORT(A[mid...n])',
      '  ',
      '  return MERGE(left, right)',
      '',
      'MERGE(left, right)',
      '  result = []',
      '  i, j = 0, 0',
      '  ',
      '  while i < length(left) and j < length(right)',
      '    if left[i] ≤ right[j]',
      '      append left[i] to result; i++',
      '    else',
      '      append right[j] to result; j++',
      '  ',
      '  return result + remaining elements',
    ],
  },
};