import { AlgorithmCode } from '@/types/algorithm';

export const sudokuCode: Record<string, AlgorithmCode> = {
  javascript: {
    language: 'javascript',
    lines: [
      'function solveSudoku(board) {',
      '  function isValid(row, col, num) {',
      '    for (let i = 0; i < 9; i++) {',
      '      if (board[row][i] === num) return false;',
      '      if (board[i][col] === num) return false;',
      '    }',
      '    const boxRow = Math.floor(row / 3) * 3;',
      '    const boxCol = Math.floor(col / 3) * 3;',
      '    for (let i = 0; i < 3; i++) {',
      '      for (let j = 0; j < 3; j++) {',
      '        if (board[boxRow + i][boxCol + j] === num)',
      '          return false;',
      '      }',
      '    }',
      '    return true;',
      '  }',
      '  ',
      '  function solve() {',
      '    for (let row = 0; row < 9; row++) {',
      '      for (let col = 0; col < 9; col++) {',
      '        if (board[row][col] === 0) {',
      '          for (let num = 1; num <= 9; num++) {',
      '            if (isValid(row, col, num)) {',
      '              board[row][col] = num;',
      '              if (solve()) return true;',
      '              board[row][col] = 0; // backtrack',
      '            }',
      '          }',
      '          return false;',
      '        }',
      '      }',
      '    }',
      '    return true; // solved',
      '  }',
      '  ',
      '  solve();',
      '  return board;',
      '}',
    ],
  },
  python: {
    language: 'python',
    lines: [
      'def solve_sudoku(board):',
      '    def is_valid(row, col, num):',
      '        for i in range(9):',
      '            if board[row][i] == num:',
      '                return False',
      '            if board[i][col] == num:',
      '                return False',
      '        box_row = (row // 3) * 3',
      '        box_col = (col // 3) * 3',
      '        for i in range(3):',
      '            for j in range(3):',
      '                if board[box_row + i][box_col + j] == num:',
      '                    return False',
      '        return True',
      '    ',
      '    def solve():',
      '        for row in range(9):',
      '            for col in range(9):',
      '                if board[row][col] == 0:',
      '                    for num in range(1, 10):',
      '                        if is_valid(row, col, num):',
      '                            board[row][col] = num',
      '                            if solve():',
      '                                return True',
      '                            board[row][col] = 0  # backtrack',
      '                    return False',
      '        return True  # solved',
      '    ',
      '    solve()',
      '    return board',
    ],
  },
  pseudocode: {
    language: 'pseudocode',
    lines: [
      'SOLVE-SUDOKU(board)',
      '  IS-VALID(row, col, num)',
      '    for i = 0 to 8',
      '      if board[row][i] = num then return false',
      '      if board[i][col] = num then return false',
      '    boxRow = floor(row / 3) * 3',
      '    boxCol = floor(col / 3) * 3',
      '    for i = 0 to 2',
      '      for j = 0 to 2',
      '        if board[boxRow+i][boxCol+j] = num',
      '          return false',
      '    return true',
      '  ',
      '  SOLVE()',
      '    for row = 0 to 8',
      '      for col = 0 to 8',
      '        if board[row][col] = 0',
      '          for num = 1 to 9',
      '            if IS-VALID(row, col, num)',
      '              board[row][col] = num',
      '              if SOLVE() then return true',
      '              board[row][col] = 0  // backtrack',
      '          return false',
      '    return true  // solved',
      '  ',
      '  SOLVE()',
      '  return board',
    ],
  },
};
